#!/bin/bash
set -euo pipefail

declare DOCKER_USER="hkjn"
declare DOCKER_IMAGE="terraform"
declare ARCH="$(uname -m)"
declare BUILD_DIR="$(mktemp -d)"
declare BASEIMAGE="hkjn/alpine:$(uname -m)"
declare TAG="$DOCKER_USER/$DOCKER_IMAGE"

sed "s|{{ARG_FROM}}|${BASEIMAGE}|g" Dockerfile.in > $BUILD_DIR/Dockerfile
cp hashicorp.asc "$BUILD_DIR/"
[[ $ARCH = "x86_64" ]] || {
  sed -i "s/FROM hkjn\//FROM hkjn\/$ARCH-/" "$BUILD_DIR/Dockerfile"
  DOCKER_IMAGE="$ARCH-$DOCKER_IMAGE"
}

echo "Building $TAG in $BUILD_DIR"
docker build -t $TAG "$BUILD_DIR/"
NO_PUSH=${NO_PUSH:-""}
[[ "$NO_PUSH" ]] || docker push $TAG
