#!/bin/bash
set -euo pipefail

declare DOCKER_USER="hkjn"
declare DOCKER_IMAGE="terraform"
declare CPU_ARCH="$(uname -m)"
declare TF_ARCH=""
declare DOCKER_ARCH=""

if [[ "${CPU_ARCH}" = "x86_64" ]]; then
	TF_ARCH="linux_amd64"
	DOCKER_ARCH="amd64"
elif [[ "${CPU_ARCH}" = "armv7l" ]]; then
	TF_ARCH="linux_arm"
	DOCKER_ARCH="arm"
else
	echo "FATAL: Unsupported CPU arch ${CPU_ARCH}." >&2
	exit 1
fi

declare TAG="${DOCKER_USER}/${DOCKER_IMAGE}:${DOCKER_ARCH}"
echo "Building ${TAG}"
docker build --build-arg tf_arch=${TF_ARCH} -t ${TAG} .
NO_PUSH=${NO_PUSH:-""}
[[ "$NO_PUSH" ]] || docker push $TAG
